### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jameschuh** [go-gota/gota#167]
when I apply aggregation for a dataframe ,it happen a panic error like this:

> panic: runtime error: invalid memory address or nil pointer dereference

the full error stack as follow:

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x20 pc=0x38c064]

goroutine 1 [running]:
github.com/go-gota/gota/series.Series.Len(...)
        D:/ProgramFiles/goplus/pkg/mod/github.com/go-gota/gota@v0.11.0/series/series.go:560
github.com/go-gota/gota/dataframe.Groups.Aggregation(0xc005d41b30, 0xc000270f00, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        D:/ProgramFiles/goplus/pkg/mod/github.com/go-gota/gota@v0.11.0/dataframe/dataframe.go:504 +0x904
```

and my code like this :

```go
agg := gdf.Aggregation([]dataframe.AggregationType{dataframe.Aggregation_COUNT}, []string{"countn"})
```

how can i solve it ? thank you.

**Comment by jameschuh** [comment]
Thank you for your reply.

go version go1.16.6 windows/amd64
gota : v0.12.0


my code :

```go
gdf := dfs.GroupBy("key1","key2")
agg := gdf.Aggregation([]dataframe.AggregationType{dataframe.Aggregation_COUNT}, []string{"countn"})
```

I read the api and find the return value of GroupBy() is *Group and the Aggregation is called by Group, then I modify the code as

```go
gdf := dfs.GroupBy("key1","key2")
gdfv := *gdf
agg := gdfv.Aggregation([]dataframe.AggregationType{dataframe.Aggregation_COUNT}, []string{"countn"})
``` 

but I get the same error.

**Comment by jameschuh** [comment]
sorry for my carelessness.

I modify the code 
```go
agg := gdf.Aggregation([]dataframe.AggregationType{dataframe.Aggregation_COUNT}, []string{"机构","性别"})
```
and another error happened

```shell
DataFrame error: Aggregation: len(typs) != len(colanmes)
```

then I see the sourcecode of dataframe, and it require the size of []AggregationType and the size of colanmes must keep the same. I think I can aggregation on two dimensions and get the count/sum  or other result.

According to the error tips, I change my code:

```go
agg := gdf.Aggregation([]dataframe.AggregationType{dataframe.Aggregation_COUNT,dataframe.Aggregation_COUNT}, []string{"分公司","合同类型"})
```

It return the duplicate value, like this:

```xml
分公司      分公司_COUNT 合同类型     合同类型_COUNT
0: 山东省分公司   6.000000  代理合同     6.000000
1: 四川省分公司   5.000000  劳动合同     5.000000
2: 山东省分公司   2.000000  劳动合同     2.000000
3: 河北省分公司   19.000000 代理合同     19.000000
4: 北京分公司    11.000000 劳动合同     11.000000
5: 四川省分公司   2.000000  代理合同     2.000000
6: 湖南省分公司   15.000000 代理合同     15.000000
7: 辽宁省分公司   3.000000  劳动合同     3.000000
8: 湖南省分公司   3.000000  劳动合同     3.000000
9: 上海分公司    1.000000  劳动合同     1.000000
```

but I just want :

```xml
分公司       合同类型     COUNT
0: 山东省分公司     代理合同     6.000000
1: 四川省分公司    劳动合同     5.000000
2: 山东省分公司    劳动合同     2.000000
3: 河北省分公司    代理合同     19.000000
4: 北京分公司     劳动合同     11.000000
5: 四川省分公司     代理合同     2.000000
6: 湖南省分公司    代理合同     15.000000
7: 辽宁省分公司     劳动合同     3.000000
8: 湖南省分公司    劳动合同     3.000000
9: 上海分公司      劳动合同     1.000000
```

**Comment by jameschuh** [comment]
yes , It's just what I want.

Thank you @chrmang 

Maybe I haven't understand how to use it . but I'm applying it combined with excelize to process data in excel , thank you for your great work!!👍🏻
